### ISSUE TITLE
Fixes in footer

### ISSUE THREAD

**Issue by durgeshdeo** [swciitg/Hab-Portal#5]
Currently:
![Screenshot 2024-10-23 225301](https://github.com/user-attachments/assets/46a3f2e8-1d66-4227-85c1-61472725a430)

Desired:
![image](https://github.com/user-attachments/assets/f8c9178b-2675-4b58-9e9f-4f855fa61c6c)

**Comment by laladwesh** [comment]
hey @durgeshdeo can you assign me this?

**Comment by durgeshdeo** [comment]
> hey @durgeshdeo can you assign me this?

Assigned to you @laladwesh
