### ISSUE TITLE
Fixes in searchbar

### ISSUE THREAD

**Issue by durgeshdeo** [swciitg/Hab-Portal#7]
Current:
![Screenshot 2024-10-23 230644](https://github.com/user-attachments/assets/4b3ac0e7-403d-4481-abf1-e69b21ba07bb)

Desired:
![Screenshot 2024-10-23 230634](https://github.com/user-attachments/assets/e3969758-a3e8-4f0c-9d81-2c0b60b51b01)

**Comment by laladwesh** [comment]
hey @durgeshdeo can i work on this issue?

**Comment by durgeshdeo** [comment]
> hey @durgeshdeo can i work on this issue?

Assigned to you @laladwesh
