### ISSUE TITLE
Fix the alignment on each page

### ISSUE THREAD

**Issue by durgeshdeo** [swciitg/Hab-Portal#8]
Current:
![Screenshot 2024-10-23 232129](https://github.com/user-attachments/assets/62e08685-1ca4-417f-88df-8b00e362c0e5)

Desired:
![Screenshot 2024-10-23 232140](https://github.com/user-attachments/assets/b56821a5-a314-47a5-b555-f1ffefda9ad5)

Make the navbar, pills and content in proper line as shown above

**Comment by laladwesh** [comment]
hey @durgeshdeo can you assign me this?

**Comment by durgeshdeo** [comment]
> hey @durgeshdeo can you assign me this?

Assigned to you @laladwesh
